export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  PACKED: 'PACKED',
  DELIVERED: 'DELIVERED',
  PARTIALLY_RETURNED: 'PARTIALLY_RETURNED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const REQUEST_STATUS_LABELS = {
  [REQUEST_STATUS.PENDING]: 'Pendiente',
  [REQUEST_STATUS.APPROVED]: 'Aprobada',
  [REQUEST_STATUS.PACKED]: 'Empacada',
  [REQUEST_STATUS.DELIVERED]: 'Entregada',
  [REQUEST_STATUS.PARTIALLY_RETURNED]: 'Devolución parcial',
  [REQUEST_STATUS.COMPLETED]: 'Completada',
  [REQUEST_STATUS.REJECTED]: 'Rechazada',
  [REQUEST_STATUS.CANCELLED]: 'Cancelada',
};

export const REQUEST_STATUS_COLORS = {
  [REQUEST_STATUS.PENDING]: 'warning',
  [REQUEST_STATUS.APPROVED]: 'success',
  [REQUEST_STATUS.PACKED]: 'info',
  [REQUEST_STATUS.DELIVERED]: 'primary',
  [REQUEST_STATUS.PARTIALLY_RETURNED]: 'secondary',
  [REQUEST_STATUS.COMPLETED]: 'default',
  [REQUEST_STATUS.REJECTED]: 'error',
  [REQUEST_STATUS.CANCELLED]: 'error',
};

export const REQUEST_STATUS_LIST = [
  REQUEST_STATUS.PENDING,
  REQUEST_STATUS.APPROVED,
  REQUEST_STATUS.PACKED,
  REQUEST_STATUS.DELIVERED,
  REQUEST_STATUS.PARTIALLY_RETURNED,
  REQUEST_STATUS.COMPLETED,
  REQUEST_STATUS.REJECTED,
  REQUEST_STATUS.CANCELLED,
];
